# Definitions of pre-commit hooks.

repos:
# Replace tabs with 4 white spaces.
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: remove-tabs
# isort: Sort Python imports.
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
# black: Format Python files.
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
# Collection of predefined pre-commit hooks.
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    # Remove trailing white spaces.
    -   id: trailing-whitespace
    # Make sure file ends in a new line.
    -   id: end-of-file-fixer
    # flake8: linter for Python.
    -   id: flake8
        args: [--max-line-length=88] # use same line length as black
    # Check YAML files for parseable syntax.
    -   id: check-yaml
    # Sort simple YAML files.
    -   id: sort-simple-yaml
        files: '^.*\.yaml'
# mypy: Type checking.
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        args: [--disallow-untyped-defs]
        exclude: tests
# pydocstyle: Check format of doc strings.
-   repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
    -   id: pydocstyle
        exclude: tests
